TITULO_PRINCIPAL = 'Tech Challenge 4 | FIAP'
TITULO_INTRODUCAO = 'Introdução'
TITULO_HISTORIA = 'História sobre o preço'
TITULO_ANALISE_EXPLORATORIA = 'Análise exploratória'
TITULO_MODELO = 'Modelo'
TITULO_CONCLUSAO = 'Conclusão'
TITULO_REFERENCIAS = 'Referências'